Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 260, in _request
    result = self._get_body(response)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 287, in _get_body
    api_status, body.get("error_message"))
googlemaps.exceptions._OverQueryLimit: OVER_QUERY_LIMIT (You have exceeded your daily request quota for this API.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "buildDatabase.py", line 54, in <module>
    location = gmaps.geocode(city)[0]['geometry']['location']
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 365, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/geocoding.py", line 68, in geocode
    return client._request("/maps/api/geocode/json", params).get("results", [])
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 270, in _request
    extract_body, requests_kwargs, post_json)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 270, in _request
    extract_body, requests_kwargs, post_json)
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 270, in _request
    extract_body, requests_kwargs, post_json)
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.6/site-packages/googlemaps/client.py", line 210, in _request
    raise googlemaps.exceptions.Timeout()
googlemaps.exceptions.Timeout
